name: publish
on:
  push:
    branches:
      - main
      - dev

jobs:
  version:
    concurrency:
      group: ${{github.workflow}}-version
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.version.outputs.version}}
      tag: ${{steps.version.outputs.tag}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
      - name: test
        run: |
          go test ./internal/versionctl
      - name: version
        id: version
        run: |
          version="$(go run ./cmd/versionctl/versionctl.go next)"
          tag="$(go run ./cmd/versionctl/versionctl.go convert "${version}" git)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
          echo "tag=${tag}" >> "${GITHUB_OUTPUT}"
      - name: tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.version.outputs.tag}}',
              sha: context.sha
            })

  build:
    needs: version
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [arm64, amd64]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
      - name: build
        run: |
          echo "${{needs.version.outputs.version}}" > internal/versionctl/version.txt
          env GOOS="${{matrix.os}}" GOARCH="${{matrix.arch}}" go build -o "versionctl-${{matrix.os}}-${{matrix.arch}}" ./cmd/versionctl/versionctl.go
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: versionctl-${{matrix.os}}-${{matrix.arch}}
          path: versionctl-${{matrix.os}}-${{matrix.arch}}

  publish:
    runs-on: ubuntu-latest
    needs: [version, build]
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: versionctl-*
          merge-multiple: true
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*
          make_latest: ${{github.ref == 'refs/heads/main'}}
          prerelease: ${{github.ref != 'refs/heads/main'}}
          tag_name: ${{needs.version.outputs.tag}}
          target_commitish: ${{github.sha}}
